#!/usr/bin/env python3
"""Interactive setup wizard for burnr8 — prompts for credentials and saves to ~/.burnr8/.env."""

import os
import stat
import sys
from pathlib import Path

BURNR8_DIR = Path.home() / ".burnr8"
ENV_FILE = BURNR8_DIR / ".env"


def _prompt(label: str, current: str | None = None, required: bool = True) -> str:
    """Prompt for a value, showing the current one if it exists."""
    if current:
        display = current[:8] + "..." if len(current) > 11 else current
        raw = input(f"  {label} [{display}]: ").strip()
        return raw if raw else current
    while True:
        raw = input(f"  {label}: ").strip()
        if raw or not required:
            return raw
        print("    This field is required.")


def _load_existing() -> dict[str, str]:
    """Load existing credentials from ~/.burnr8/.env if it exists."""
    creds: dict[str, str] = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                creds[key.strip()] = value.strip().strip("\"'")
    return creds


def _save_env(creds: dict[str, str]) -> None:
    """Write credentials to ~/.burnr8/.env with 0600 permissions."""
    BURNR8_DIR.mkdir(parents=True, exist_ok=True, mode=0o700)

    lines = [
        "# burnr8 credentials — generated by burnr8-setup",
        f"GOOGLE_ADS_DEVELOPER_TOKEN={creds.get('GOOGLE_ADS_DEVELOPER_TOKEN', '')}",
        f"GOOGLE_ADS_CLIENT_ID={creds.get('GOOGLE_ADS_CLIENT_ID', '')}",
        f"GOOGLE_ADS_CLIENT_SECRET={creds.get('GOOGLE_ADS_CLIENT_SECRET', '')}",
        f"GOOGLE_ADS_REFRESH_TOKEN={creds.get('GOOGLE_ADS_REFRESH_TOKEN', '')}",
    ]
    login_id = creds.get("GOOGLE_ADS_LOGIN_CUSTOMER_ID")
    if login_id:
        lines.append(f"GOOGLE_ADS_LOGIN_CUSTOMER_ID={login_id}")

    # Write with restrictive permissions
    fd = os.open(ENV_FILE, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with open(fd, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\n  Saved to {ENV_FILE}")
    print(f"  Permissions: {oct(stat.S_IMODE(os.stat(ENV_FILE).st_mode))}")


def _main():
    print("\n  burnr8 setup")
    print("  " + "-" * 40)

    print("\n  Get your credentials: https://burnrate.sh/docs/getting-started/credentials")
    print("  Or skip setup and use burnr8 Cloud: https://burnrate.sh\n")

    existing = _load_existing()
    if existing:
        print(f"  Found existing credentials at {ENV_FILE}")
        print("  Press Enter to keep current values, or type a new one.\n")

    # Collect credentials
    creds = {}
    creds["GOOGLE_ADS_DEVELOPER_TOKEN"] = _prompt(
        "Developer token", existing.get("GOOGLE_ADS_DEVELOPER_TOKEN")
    )
    creds["GOOGLE_ADS_CLIENT_ID"] = _prompt(
        "OAuth2 client ID", existing.get("GOOGLE_ADS_CLIENT_ID")
    )
    creds["GOOGLE_ADS_CLIENT_SECRET"] = _prompt(
        "OAuth2 client secret", existing.get("GOOGLE_ADS_CLIENT_SECRET")
    )
    creds["GOOGLE_ADS_REFRESH_TOKEN"] = _prompt(
        "Refresh token", existing.get("GOOGLE_ADS_REFRESH_TOKEN")
    )

    # Optional: login customer ID (validate numeric)
    login_id = _prompt(
        "Login customer ID (MCC, optional)",
        existing.get("GOOGLE_ADS_LOGIN_CUSTOMER_ID"),
        required=False,
    )
    if login_id:
        cleaned = login_id.replace("-", "")
        if cleaned and not cleaned.isdigit():
            print(
                f"  Warning: '{cleaned}' contains non-numeric characters."
                " Customer IDs are 10 digits."
            )
        creds["GOOGLE_ADS_LOGIN_CUSTOMER_ID"] = cleaned

    # Save
    _save_env(creds)

    print("\n  Next steps:")
    print("    1. Restart Claude Code")
    print("    2. Try: list_accessible_accounts")
    print()


def main():
    try:
        _main()
    except KeyboardInterrupt:
        print("\n\n  Setup cancelled. No credentials were saved.")
        sys.exit(0)
    except OSError as e:
        # File system errors (permissions, disk full, etc.)
        print(f"\n  Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\n  Setup failed: {e}")
        print("  You can re-run burnr8-setup or set credentials manually in ~/.burnr8/.env")
        sys.exit(1)


if __name__ == "__main__":
    main()
