#!/usr/bin/env python3
"""Interactive setup wizard for burnr8 — prompts for credentials and saves to ~/.burnr8/.env."""

import getpass
import os
import stat
import sys
import tempfile
from pathlib import Path

from dotenv import dotenv_values, set_key

BURNR8_DIR = Path.home() / ".burnr8"
ENV_FILE = BURNR8_DIR / ".env"


def _prompt(label: str, current: str | None = None, required: bool = True, *, secret: bool = False) -> str:
    """Prompt for a value, showing the current one if it exists."""
    read = getpass.getpass if secret else input
    if current is not None and current != "":
        display = "saved" if secret else current[:8] + "..." if len(current) > 11 else current
        raw = read(f"  {label} [{display}]: ").strip()
        return raw if raw else current
    while True:
        raw = read(f"  {label}: ").strip()
        if raw or not required:
            return raw
        print("    This field is required.")


def _load_existing() -> dict[str, str]:
    """Load existing credentials from ~/.burnr8/.env if it exists."""
    creds: dict[str, str] = {}
    if not ENV_FILE.exists():
        return creds
    try:
        creds = {key: value for key, value in dotenv_values(ENV_FILE, interpolate=False).items() if value is not None}
    except (OSError, UnicodeDecodeError) as e:
        print(f"  Warning: Could not read {ENV_FILE}: {e}")
        print("  Starting fresh.\n")
    return creds


def _save_env(creds: dict[str, str]) -> None:
    """Write credentials to ~/.burnr8/.env with 0600 permissions (atomic)."""
    BURNR8_DIR.mkdir(parents=True, exist_ok=True, mode=0o700)

    if ENV_FILE.is_symlink():
        raise ValueError("Refusing to write credentials through a symlink.")
    content = ENV_FILE.read_text() if ENV_FILE.exists() else "# burnr8 credentials — generated by burnr8-setup\n"

    # Atomic write: temp file + rename prevents data loss on interrupt
    fd, tmp_path = tempfile.mkstemp(dir=BURNR8_DIR, prefix=".env.", suffix=".tmp")
    try:
        with open(fd, "w") as f:
            f.write(content)
        for key, value in creds.items():
            set_key(tmp_path, key, value, quote_mode="always")
        os.chmod(tmp_path, 0o600)
        os.rename(tmp_path, ENV_FILE)
    except BaseException:
        os.unlink(tmp_path)
        raise

    print(f"\n  Saved to {ENV_FILE}")
    print(f"  Permissions: {oct(stat.S_IMODE(os.stat(ENV_FILE).st_mode))}")


def _main() -> None:
    print("\n  burnr8 setup")
    print("  " + "-" * 40)

    print("\n  Get your credentials: https://burnrate.sh/docs/getting-started/credentials")
    print("  Or skip setup and use burnr8 Cloud: https://burnrate.sh\n")

    existing = _load_existing()
    if existing:
        print(f"  Found existing credentials at {ENV_FILE}")
        print("  Press Enter to keep current values, or type a new one.\n")

    # Collect credentials
    creds = dict(existing)
    creds["GOOGLE_ADS_DEVELOPER_TOKEN"] = _prompt(
        "Developer token", existing.get("GOOGLE_ADS_DEVELOPER_TOKEN"), secret=True
    )
    creds["GOOGLE_ADS_CLIENT_ID"] = _prompt("OAuth2 client ID", existing.get("GOOGLE_ADS_CLIENT_ID"))
    creds["GOOGLE_ADS_CLIENT_SECRET"] = _prompt(
        "OAuth2 client secret", existing.get("GOOGLE_ADS_CLIENT_SECRET"), secret=True
    )
    creds["GOOGLE_ADS_REFRESH_TOKEN"] = _prompt("Refresh token", existing.get("GOOGLE_ADS_REFRESH_TOKEN"), secret=True)

    # Optional: login customer ID (validate numeric)
    login_id = _prompt(
        "Login customer ID (MCC, optional)",
        existing.get("GOOGLE_ADS_LOGIN_CUSTOMER_ID"),
        required=False,
    )
    if login_id:
        cleaned = login_id.replace("-", "")
        if cleaned and not cleaned.isdigit():
            print(f"  Warning: '{cleaned}' contains non-numeric characters. Customer IDs are 10 digits.")
        creds["GOOGLE_ADS_LOGIN_CUSTOMER_ID"] = cleaned

    print("\n  Meta Ads (optional — required for Facebook/Instagram Reels tools)")
    meta_token = _prompt("Meta access token", existing.get("META_ACCESS_TOKEN"), required=False, secret=True)
    if meta_token:
        creds["META_ACCESS_TOKEN"] = meta_token
        meta_app_secret = _prompt(
            "Meta app secret (recommended)", existing.get("META_APP_SECRET"), required=False, secret=True
        )
        if meta_app_secret:
            creds["META_APP_SECRET"] = meta_app_secret
        meta_account_id = _prompt(
            "Default Meta ad account ID (optional)", existing.get("META_AD_ACCOUNT_ID"), required=False
        )
        if meta_account_id:
            cleaned_meta_id = meta_account_id.removeprefix("act_")
            if not cleaned_meta_id.isdigit():
                print(f"  Warning: '{cleaned_meta_id}' is not a numeric Meta ad account ID.")
            creds["META_AD_ACCOUNT_ID"] = cleaned_meta_id
        creds["META_GRAPH_API_VERSION"] = _prompt(
            "Meta Graph API version", existing.get("META_GRAPH_API_VERSION", "v25.0"), required=False
        )
        media_root = _prompt(
            "Approved local photo directory (optional)", existing.get("BURNR8_MEDIA_ROOT"), required=False
        )
        if media_root:
            creds["BURNR8_MEDIA_ROOT"] = media_root

    print("\n  Google SEO Intelligence (optional)")
    gsc_refresh = _prompt(
        "Search Console refresh token (webmasters.readonly)",
        existing.get("GOOGLE_SEARCH_CONSOLE_REFRESH_TOKEN"),
        required=False,
        secret=True,
    )
    if gsc_refresh:
        creds["GOOGLE_SEARCH_CONSOLE_REFRESH_TOKEN"] = gsc_refresh
        gsc_client_id = _prompt(
            "Search Console OAuth client ID (Enter reuses Google Ads)",
            existing.get("GOOGLE_SEARCH_CONSOLE_CLIENT_ID"),
            required=False,
        )
        if gsc_client_id:
            creds["GOOGLE_SEARCH_CONSOLE_CLIENT_ID"] = gsc_client_id
        gsc_client_secret = _prompt(
            "Search Console OAuth client secret (Enter reuses Google Ads)",
            existing.get("GOOGLE_SEARCH_CONSOLE_CLIENT_SECRET"),
            required=False,
            secret=True,
        )
        if gsc_client_secret:
            creds["GOOGLE_SEARCH_CONSOLE_CLIENT_SECRET"] = gsc_client_secret
        gsc_property = _prompt(
            "Default property, e.g. sc-domain:example.com",
            existing.get("GOOGLE_SEARCH_CONSOLE_PROPERTY"),
            required=False,
        )
        if gsc_property:
            creds["GOOGLE_SEARCH_CONSOLE_PROPERTY"] = gsc_property

    pagespeed_key = _prompt(
        "PageSpeed API key (optional)", existing.get("GOOGLE_PAGESPEED_API_KEY"), required=False, secret=True
    )
    if pagespeed_key:
        creds["GOOGLE_PAGESPEED_API_KEY"] = pagespeed_key
    crux_key = _prompt(
        "CrUX API key (Enter reuses PageSpeed key)", existing.get("GOOGLE_CRUX_API_KEY"), required=False, secret=True
    )
    if crux_key:
        creds["GOOGLE_CRUX_API_KEY"] = crux_key
    crawl_limit = _prompt(
        "SEO crawler hard page cap (optional, default 100)",
        existing.get("BURNR8_SEO_MAX_CRAWL_PAGES"),
        required=False,
    )
    if crawl_limit:
        if not crawl_limit.isdigit() or int(crawl_limit) < 1:
            print(f"  Warning: '{crawl_limit}' is not a positive crawler page cap; using 100.")
            crawl_limit = "100"
        creds["BURNR8_SEO_MAX_CRAWL_PAGES"] = crawl_limit

    # Save
    _save_env(creds)

    print("\n  Next steps:")
    print("    1. Restart Claude Code")
    print("    2. Try: list_accessible_accounts, meta_list_ad_accounts, or gsc_list_properties")
    print()


def main() -> None:
    try:
        _main()
    except KeyboardInterrupt:
        print("\n\n  Setup interrupted.")
        sys.exit(0)
    except EOFError:
        print("\n\n  burnr8-setup requires an interactive terminal.")
        print("  Set credentials manually in ~/.burnr8/.env")
        sys.exit(1)
    except OSError as e:
        print(f"\n  Error: {e}")
        sys.exit(1)
    except Exception as e:
        import traceback

        print(f"\n  Unexpected error: {e}")
        traceback.print_exc()
        print("  Please report this at https://github.com/HarrisonHesslink/burnr8/issues")
        sys.exit(1)


if __name__ == "__main__":
    main()
